[platformio]
default_envs = sensor

[env:sensor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D I2C_SDA_PIN=21
  -D I2C_SCL_PIN=22
  -D MPU_ADDR=0x68
  -D DEVICE_ID='"footsensor"'
  -D RECEIVER_MAC={0xFF,0xFF,0xFF,0xFF,0xFF,0xFF}
build_src_filter = +<common/> +<sensor/>

[env:receiver]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D DEVICE_ID='"footsensor-receiver"'
build_src_filter = +<receiver/>
