[platformio]
default_envs = main

[env:main]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -D I2C_SDA_PIN=21
  -D I2C_SCL_PIN=22
  -D MPU_ADDR=0x68
  -D WIFI_SSID='"your-ssid"'
  -D WIFI_PASS='"your-password"'
  -D PC_IP='"192.168.1.100"'
  -D UDP_PORT=5005
  -D DEVICE_ID='"footsensor"'